# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mzMLextractor_UI.ui'
#
# Created: Wed Nov 02 12:29:38 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabframe = QtGui.QTabWidget(self.centralwidget)
        self.tabframe.setGeometry(QtCore.QRect(6, 9, 781, 521))
        self.tabframe.setObjectName("tabframe")
        self.extract_ms_level_tab = QtGui.QWidget()
        self.extract_ms_level_tab.setObjectName("extract_ms_level_tab")
        self.gridLayoutWidget = QtGui.QWidget(self.extract_ms_level_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 751, 491))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tab_a_savexlsxfolder_pb = QtGui.QPushButton(self.gridLayoutWidget)
        self.tab_a_savexlsxfolder_pb.setObjectName("tab_a_savexlsxfolder_pb")
        self.gridLayout.addWidget(self.tab_a_savexlsxfolder_pb, 5, 2, 1, 1)
        self.tab_a_statusextractor_pte = QtGui.QPlainTextEdit(self.gridLayoutWidget)
        self.tab_a_statusextractor_pte.setMinimumSize(QtCore.QSize(0, 40))
        self.tab_a_statusextractor_pte.setMaximumSize(QtCore.QSize(16777215, 150))
        self.tab_a_statusextractor_pte.setObjectName("tab_a_statusextractor_pte")
        self.gridLayout.addWidget(self.tab_a_statusextractor_pte, 6, 1, 1, 1)
        self.tab_a_statusmerger_pte = QtGui.QPlainTextEdit(self.gridLayoutWidget)
        self.tab_a_statusmerger_pte.setMinimumSize(QtCore.QSize(0, 50))
        self.tab_a_statusmerger_pte.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tab_a_statusmerger_pte.setObjectName("tab_a_statusmerger_pte")
        self.gridLayout.addWidget(self.tab_a_statusmerger_pte, 9, 1, 1, 1)
        self.tab_a_csvfolder_le = QtGui.QLineEdit(self.gridLayoutWidget)
        self.tab_a_csvfolder_le.setObjectName("tab_a_csvfolder_le")
        self.gridLayout.addWidget(self.tab_a_csvfolder_le, 8, 1, 1, 1)
        self.tab_a_7_lb = QtGui.QLabel(self.gridLayoutWidget)
        self.tab_a_7_lb.setObjectName("tab_a_7_lb")
        self.gridLayout.addWidget(self.tab_a_7_lb, 8, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tab_a_clearall_pb = QtGui.QPushButton(self.gridLayoutWidget)
        self.tab_a_clearall_pb.setObjectName("tab_a_clearall_pb")
        self.verticalLayout.addWidget(self.tab_a_clearall_pb)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout, 2, 2, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tab_a_addmzml_pb = QtGui.QPushButton(self.gridLayoutWidget)
        self.tab_a_addmzml_pb.setObjectName("tab_a_addmzml_pb")
        self.horizontalLayout_2.addWidget(self.tab_a_addmzml_pb)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.tab_a_3_lb = QtGui.QLabel(self.gridLayoutWidget)
        self.tab_a_3_lb.setObjectName("tab_a_3_lb")
        self.horizontalLayout_2.addWidget(self.tab_a_3_lb)
        self.tab_a_addmzmlfolder_pb = QtGui.QPushButton(self.gridLayoutWidget)
        self.tab_a_addmzmlfolder_pb.setObjectName("tab_a_addmzmlfolder_pb")
        self.horizontalLayout_2.addWidget(self.tab_a_addmzmlfolder_pb)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tab_a_10_lb = QtGui.QLabel(self.gridLayoutWidget)
        self.tab_a_10_lb.setObjectName("tab_a_10_lb")
        self.horizontalLayout.addWidget(self.tab_a_10_lb)
        self.tab_a_mzstart_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.tab_a_mzstart_dspb.setDecimals(4)
        self.tab_a_mzstart_dspb.setMaximum(5000.0)
        self.tab_a_mzstart_dspb.setProperty("value", 350.0)
        self.tab_a_mzstart_dspb.setObjectName("tab_a_mzstart_dspb")
        self.horizontalLayout.addWidget(self.tab_a_mzstart_dspb)
        self.tab_a_11_lb = QtGui.QLabel(self.gridLayoutWidget)
        self.tab_a_11_lb.setObjectName("tab_a_11_lb")
        self.horizontalLayout.addWidget(self.tab_a_11_lb)
        self.tab_a_mzend_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.tab_a_mzend_dspb.setDecimals(4)
        self.tab_a_mzend_dspb.setMaximum(9000.0)
        self.tab_a_mzend_dspb.setProperty("value", 1000.0)
        self.tab_a_mzend_dspb.setObjectName("tab_a_mzend_dspb")
        self.horizontalLayout.addWidget(self.tab_a_mzend_dspb)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 1, 1, 1)
        self.tab_a_5_lb = QtGui.QLabel(self.gridLayoutWidget)
        self.tab_a_5_lb.setObjectName("tab_a_5_lb")
        self.gridLayout.addWidget(self.tab_a_5_lb, 5, 0, 1, 1)
        self.tab_a_2_lb = QtGui.QLabel(self.gridLayoutWidget)
        self.tab_a_2_lb.setObjectName("tab_a_2_lb")
        self.gridLayout.addWidget(self.tab_a_2_lb, 1, 0, 1, 1)
        self.tab_a_runextractor_pb = QtGui.QPushButton(self.gridLayoutWidget)
        self.tab_a_runextractor_pb.setObjectName("tab_a_runextractor_pb")
        self.gridLayout.addWidget(self.tab_a_runextractor_pb, 6, 0, 1, 1)
        self.tab_a_savecsv_pb = QtGui.QPushButton(self.gridLayoutWidget)
        self.tab_a_savecsv_pb.setObjectName("tab_a_savecsv_pb")
        self.gridLayout.addWidget(self.tab_a_savecsv_pb, 8, 2, 1, 1)
        self.tab_a_xlsxfolder_le = QtGui.QLineEdit(self.gridLayoutWidget)
        self.tab_a_xlsxfolder_le.setObjectName("tab_a_xlsxfolder_le")
        self.gridLayout.addWidget(self.tab_a_xlsxfolder_le, 5, 1, 1, 1)
        self.tab_a_infiles_pte = QtGui.QPlainTextEdit(self.gridLayoutWidget)
        self.tab_a_infiles_pte.setMinimumSize(QtCore.QSize(0, 50))
        self.tab_a_infiles_pte.setMaximumSize(QtCore.QSize(16777215, 150))
        self.tab_a_infiles_pte.setObjectName("tab_a_infiles_pte")
        self.gridLayout.addWidget(self.tab_a_infiles_pte, 2, 1, 1, 1)
        self.tab_a_1_lb = QtGui.QLabel(self.gridLayoutWidget)
        self.tab_a_1_lb.setObjectName("tab_a_1_lb")
        self.gridLayout.addWidget(self.tab_a_1_lb, 0, 1, 1, 1)
        self.tab_a_6_lb = QtGui.QLabel(self.gridLayoutWidget)
        self.tab_a_6_lb.setObjectName("tab_a_6_lb")
        self.gridLayout.addWidget(self.tab_a_6_lb, 7, 1, 1, 1)
        self.tab_a_runmerge_pb = QtGui.QPushButton(self.gridLayoutWidget)
        self.tab_a_runmerge_pb.setObjectName("tab_a_runmerge_pb")
        self.gridLayout.addWidget(self.tab_a_runmerge_pb, 9, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tab_a_8_lb = QtGui.QLabel(self.gridLayoutWidget)
        self.tab_a_8_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tab_a_8_lb.setObjectName("tab_a_8_lb")
        self.horizontalLayout_8.addWidget(self.tab_a_8_lb)
        self.tab_a_rtstart_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.tab_a_rtstart_dspb.setMaximum(300.0)
        self.tab_a_rtstart_dspb.setSingleStep(1.0)
        self.tab_a_rtstart_dspb.setProperty("value", 3.0)
        self.tab_a_rtstart_dspb.setObjectName("tab_a_rtstart_dspb")
        self.horizontalLayout_8.addWidget(self.tab_a_rtstart_dspb)
        self.tab_a_9_lb = QtGui.QLabel(self.gridLayoutWidget)
        self.tab_a_9_lb.setObjectName("tab_a_9_lb")
        self.horizontalLayout_8.addWidget(self.tab_a_9_lb)
        self.tab_a_rtend_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.tab_a_rtend_dspb.setMaximum(300.0)
        self.tab_a_rtend_dspb.setProperty("value", 20.0)
        self.tab_a_rtend_dspb.setObjectName("tab_a_rtend_dspb")
        self.horizontalLayout_8.addWidget(self.tab_a_rtend_dspb)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.tab_a_4_lb = QtGui.QLabel(self.gridLayoutWidget)
        self.tab_a_4_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tab_a_4_lb.setObjectName("tab_a_4_lb")
        self.horizontalLayout_8.addWidget(self.tab_a_4_lb)
        self.tab_a_msthreshold_spb = QtGui.QSpinBox(self.gridLayoutWidget)
        self.tab_a_msthreshold_spb.setMaximum(1000000000)
        self.tab_a_msthreshold_spb.setProperty("value", 1000)
        self.tab_a_msthreshold_spb.setObjectName("tab_a_msthreshold_spb")
        self.horizontalLayout_8.addWidget(self.tab_a_msthreshold_spb)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_8, 3, 1, 1, 1)
        self.tabframe.addTab(self.extract_ms_level_tab, "")
        self.scan_info_tab = QtGui.QWidget()
        self.scan_info_tab.setObjectName("scan_info_tab")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.scan_info_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 761, 401))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.tab_b_clearall_pb = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.tab_b_clearall_pb.setObjectName("tab_b_clearall_pb")
        self.verticalLayout_2.addWidget(self.tab_b_clearall_pb)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 2, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tab_b_3_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_3_lb.setObjectName("tab_b_3_lb")
        self.horizontalLayout_4.addWidget(self.tab_b_3_lb)
        self.tab_b_msthreshold_spb = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.tab_b_msthreshold_spb.setMaximum(999999)
        self.tab_b_msthreshold_spb.setProperty("value", 1000)
        self.tab_b_msthreshold_spb.setObjectName("tab_b_msthreshold_spb")
        self.horizontalLayout_4.addWidget(self.tab_b_msthreshold_spb)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.tab_b_4_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_4_lb.setObjectName("tab_b_4_lb")
        self.horizontalLayout_4.addWidget(self.tab_b_4_lb)
        self.tab_b_ms2threshold_spb = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.tab_b_ms2threshold_spb.setMaximum(99999)
        self.tab_b_ms2threshold_spb.setProperty("value", 10)
        self.tab_b_ms2threshold_spb.setObjectName("tab_b_ms2threshold_spb")
        self.horizontalLayout_4.addWidget(self.tab_b_ms2threshold_spb)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 4, 1, 1, 1)
        self.tab_b_1_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_1_lb.setObjectName("tab_b_1_lb")
        self.gridLayout_2.addWidget(self.tab_b_1_lb, 0, 0, 1, 1)
        self.tab_b_outpufolder_le = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.tab_b_outpufolder_le.setObjectName("tab_b_outpufolder_le")
        self.gridLayout_2.addWidget(self.tab_b_outpufolder_le, 6, 1, 1, 1)
        self.tab_b_savexlsxfolder_pb = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.tab_b_savexlsxfolder_pb.setObjectName("tab_b_savexlsxfolder_pb")
        self.gridLayout_2.addWidget(self.tab_b_savexlsxfolder_pb, 6, 2, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 7, 1, 1, 1)
        self.tab_b_5_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_5_lb.setObjectName("tab_b_5_lb")
        self.gridLayout_2.addWidget(self.tab_b_5_lb, 6, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 5, 1, 1, 1)
        self.tab_b_infiles_pte = QtGui.QPlainTextEdit(self.gridLayoutWidget_2)
        self.tab_b_infiles_pte.setObjectName("tab_b_infiles_pte")
        self.gridLayout_2.addWidget(self.tab_b_infiles_pte, 1, 1, 1, 1)
        self.tab_b_runextract_pb = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.tab_b_runextract_pb.setObjectName("tab_b_runextract_pb")
        self.gridLayout_2.addWidget(self.tab_b_runextract_pb, 8, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tab_b_addmzml_pb = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.tab_b_addmzml_pb.setObjectName("tab_b_addmzml_pb")
        self.horizontalLayout_3.addWidget(self.tab_b_addmzml_pb)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.tab_b_2_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_2_lb.setObjectName("tab_b_2_lb")
        self.horizontalLayout_3.addWidget(self.tab_b_2_lb)
        self.tab_b_addmzmlfolder_pb = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.tab_b_addmzmlfolder_pb.setObjectName("tab_b_addmzmlfolder_pb")
        self.horizontalLayout_3.addWidget(self.tab_b_addmzmlfolder_pb)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.tab_b_statusrun_pte = QtGui.QPlainTextEdit(self.gridLayoutWidget_2)
        self.tab_b_statusrun_pte.setMaximumSize(QtCore.QSize(16777215, 200))
        self.tab_b_statusrun_pte.setObjectName("tab_b_statusrun_pte")
        self.gridLayout_2.addWidget(self.tab_b_statusrun_pte, 8, 1, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tab_b_8_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_8_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tab_b_8_lb.setObjectName("tab_b_8_lb")
        self.horizontalLayout_9.addWidget(self.tab_b_8_lb)
        self.tab_b_rtstart_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.tab_b_rtstart_dspb.setMaximum(300.0)
        self.tab_b_rtstart_dspb.setSingleStep(1.0)
        self.tab_b_rtstart_dspb.setProperty("value", 3.0)
        self.tab_b_rtstart_dspb.setObjectName("tab_b_rtstart_dspb")
        self.horizontalLayout_9.addWidget(self.tab_b_rtstart_dspb)
        self.tab_b_11_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_11_lb.setObjectName("tab_b_11_lb")
        self.horizontalLayout_9.addWidget(self.tab_b_11_lb)
        self.tab_b_rtend_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.tab_b_rtend_dspb.setMaximum(300.0)
        self.tab_b_rtend_dspb.setProperty("value", 20.0)
        self.tab_b_rtend_dspb.setObjectName("tab_b_rtend_dspb")
        self.horizontalLayout_9.addWidget(self.tab_b_rtend_dspb)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem13)
        self.tab_b_10_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_10_lb.setObjectName("tab_b_10_lb")
        self.horizontalLayout_9.addWidget(self.tab_b_10_lb)
        self.tab_b_mzstart_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.tab_b_mzstart_dspb.setDecimals(4)
        self.tab_b_mzstart_dspb.setMaximum(5000.0)
        self.tab_b_mzstart_dspb.setProperty("value", 350.0)
        self.tab_b_mzstart_dspb.setObjectName("tab_b_mzstart_dspb")
        self.horizontalLayout_9.addWidget(self.tab_b_mzstart_dspb)
        self.tab_b_9_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_9_lb.setObjectName("tab_b_9_lb")
        self.horizontalLayout_9.addWidget(self.tab_b_9_lb)
        self.tab_b_mzend_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.tab_b_mzend_dspb.setDecimals(4)
        self.tab_b_mzend_dspb.setMaximum(9000.0)
        self.tab_b_mzend_dspb.setProperty("value", 1000.0)
        self.tab_b_mzend_dspb.setObjectName("tab_b_mzend_dspb")
        self.horizontalLayout_9.addWidget(self.tab_b_mzend_dspb)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem14)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 2, 1, 1, 1)
        self.tabframe.addTab(self.scan_info_tab, "")
        self.search_tab = QtGui.QWidget()
        self.search_tab.setObjectName("search_tab")
        self.gridLayoutWidget_4 = QtGui.QWidget(self.search_tab)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 751, 111))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tab_c_5_lb = QtGui.QLabel(self.gridLayoutWidget_4)
        self.tab_c_5_lb.setTextFormat(QtCore.Qt.RichText)
        self.tab_c_5_lb.setObjectName("tab_c_5_lb")
        self.gridLayout_4.addWidget(self.tab_c_5_lb, 4, 1, 1, 1)
        self.tab_c_4_lb = QtGui.QLabel(self.gridLayoutWidget_4)
        self.tab_c_4_lb.setObjectName("tab_c_4_lb")
        self.gridLayout_4.addWidget(self.tab_c_4_lb, 3, 0, 1, 1)
        self.tab_c_2_lb = QtGui.QLabel(self.gridLayoutWidget_4)
        self.tab_c_2_lb.setMaximumSize(QtCore.QSize(140, 16777215))
        self.tab_c_2_lb.setObjectName("tab_c_2_lb")
        self.gridLayout_4.addWidget(self.tab_c_2_lb, 1, 0, 1, 1)
        self.tab_c_1_lb = QtGui.QLabel(self.gridLayoutWidget_4)
        self.tab_c_1_lb.setObjectName("tab_c_1_lb")
        self.gridLayout_4.addWidget(self.tab_c_1_lb, 0, 1, 1, 1)
        self.tab_c_3_lb = QtGui.QLabel(self.gridLayoutWidget_4)
        self.tab_c_3_lb.setTextFormat(QtCore.Qt.RichText)
        self.tab_c_3_lb.setObjectName("tab_c_3_lb")
        self.gridLayout_4.addWidget(self.tab_c_3_lb, 2, 1, 1, 1)
        self.tabframe.addTab(self.search_tab, "")
        self.link_tab = QtGui.QWidget()
        self.link_tab.setObjectName("link_tab")
        self.gridLayoutWidget_3 = QtGui.QWidget(self.link_tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 761, 451))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tab_d_lipidclass_cmb = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.tab_d_lipidclass_cmb.setMinimumSize(QtCore.QSize(220, 0))
        self.tab_d_lipidclass_cmb.setObjectName("tab_d_lipidclass_cmb")
        self.tab_d_lipidclass_cmb.addItem("")
        self.tab_d_lipidclass_cmb.addItem("")
        self.tab_d_lipidclass_cmb.addItem("")
        self.tab_d_lipidclass_cmb.addItem("")
        self.tab_d_lipidclass_cmb.addItem("")
        self.tab_d_lipidclass_cmb.addItem("")
        self.tab_d_lipidclass_cmb.addItem("")
        self.tab_d_lipidclass_cmb.addItem("")
        self.horizontalLayout_6.addWidget(self.tab_d_lipidclass_cmb)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem15)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 0, 1, 1, 1)
        self.tab_d_runextract_pb = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.tab_d_runextract_pb.setObjectName("tab_d_runextract_pb")
        self.gridLayout_3.addWidget(self.tab_d_runextract_pb, 9, 0, 1, 1)
        self.tab_d_4_lb = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_4_lb.setObjectName("tab_d_4_lb")
        self.gridLayout_3.addWidget(self.tab_d_4_lb, 3, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tab_d_ms2mzml_pb = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.tab_d_ms2mzml_pb.setObjectName("tab_d_ms2mzml_pb")
        self.verticalLayout_3.addWidget(self.tab_d_ms2mzml_pb)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 3, 2, 1, 1)
        self.tab_d_lipidstable_le = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.tab_d_lipidstable_le.setObjectName("tab_d_lipidstable_le")
        self.gridLayout_3.addWidget(self.tab_d_lipidstable_le, 1, 1, 1, 1)
        self.tab_d_lipidstable_pb = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.tab_d_lipidstable_pb.setObjectName("tab_d_lipidstable_pb")
        self.gridLayout_3.addWidget(self.tab_d_lipidstable_pb, 1, 2, 1, 1)
        self.tab_d_2_lb = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_2_lb.setObjectName("tab_d_2_lb")
        self.gridLayout_3.addWidget(self.tab_d_2_lb, 1, 0, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem16, 6, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tab_d_5_lb = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_5_lb.setObjectName("tab_d_5_lb")
        self.horizontalLayout_5.addWidget(self.tab_d_5_lb)
        self.tab_d_msthreshold_spb = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.tab_d_msthreshold_spb.setMaximum(999999)
        self.tab_d_msthreshold_spb.setProperty("value", 1000)
        self.tab_d_msthreshold_spb.setObjectName("tab_d_msthreshold_spb")
        self.horizontalLayout_5.addWidget(self.tab_d_msthreshold_spb)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem17)
        self.tab_d_6_lb = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_6_lb.setObjectName("tab_d_6_lb")
        self.horizontalLayout_5.addWidget(self.tab_d_6_lb)
        self.tab_d_ms2threshold_spb = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.tab_d_ms2threshold_spb.setMaximum(99999)
        self.tab_d_ms2threshold_spb.setProperty("value", 10)
        self.tab_d_ms2threshold_spb.setObjectName("tab_d_ms2threshold_spb")
        self.horizontalLayout_5.addWidget(self.tab_d_ms2threshold_spb)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem18)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 5, 1, 1, 1)
        self.tab_d_7_lb = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_7_lb.setObjectName("tab_d_7_lb")
        self.gridLayout_3.addWidget(self.tab_d_7_lb, 7, 0, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem19, 8, 1, 1, 1)
        self.tab_d_1_lb = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_1_lb.setObjectName("tab_d_1_lb")
        self.gridLayout_3.addWidget(self.tab_d_1_lb, 0, 0, 1, 1)
        self.tab_d_xlsxpath_le = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.tab_d_xlsxpath_le.setObjectName("tab_d_xlsxpath_le")
        self.gridLayout_3.addWidget(self.tab_d_xlsxpath_le, 7, 1, 1, 1)
        self.tab_b_xlsxpath_pb = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.tab_b_xlsxpath_pb.setObjectName("tab_b_xlsxpath_pb")
        self.gridLayout_3.addWidget(self.tab_b_xlsxpath_pb, 7, 2, 1, 1)
        self.tab_d_msmzml_le = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.tab_d_msmzml_le.setObjectName("tab_d_msmzml_le")
        self.gridLayout_3.addWidget(self.tab_d_msmzml_le, 2, 1, 1, 1)
        self.tab_d_msmzml_pb = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.tab_d_msmzml_pb.setObjectName("tab_d_msmzml_pb")
        self.gridLayout_3.addWidget(self.tab_d_msmzml_pb, 2, 2, 1, 1)
        self.tab_d_ms2mzml_le = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.tab_d_ms2mzml_le.setObjectName("tab_d_ms2mzml_le")
        self.gridLayout_3.addWidget(self.tab_d_ms2mzml_le, 3, 1, 1, 1)
        self.tab_d_3_lb = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_3_lb.setObjectName("tab_d_3_lb")
        self.gridLayout_3.addWidget(self.tab_d_3_lb, 2, 0, 1, 1)
        self.tab_d_statusrun_pte = QtGui.QPlainTextEdit(self.gridLayoutWidget_3)
        self.tab_d_statusrun_pte.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tab_d_statusrun_pte.setObjectName("tab_d_statusrun_pte")
        self.gridLayout_3.addWidget(self.tab_d_statusrun_pte, 9, 1, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.tab_d_8_lb = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_8_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tab_d_8_lb.setObjectName("tab_d_8_lb")
        self.horizontalLayout_10.addWidget(self.tab_d_8_lb)
        self.tab_d_rtstart_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.tab_d_rtstart_dspb.setMaximum(300.0)
        self.tab_d_rtstart_dspb.setSingleStep(1.0)
        self.tab_d_rtstart_dspb.setProperty("value", 3.0)
        self.tab_d_rtstart_dspb.setObjectName("tab_d_rtstart_dspb")
        self.horizontalLayout_10.addWidget(self.tab_d_rtstart_dspb)
        self.tab_d_9_lb = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_9_lb.setObjectName("tab_d_9_lb")
        self.horizontalLayout_10.addWidget(self.tab_d_9_lb)
        self.tab_d_rtend_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.tab_d_rtend_dspb.setMaximum(300.0)
        self.tab_d_rtend_dspb.setProperty("value", 20.0)
        self.tab_d_rtend_dspb.setObjectName("tab_d_rtend_dspb")
        self.horizontalLayout_10.addWidget(self.tab_d_rtend_dspb)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem20)
        self.tab_d_10_lb = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_10_lb.setObjectName("tab_d_10_lb")
        self.horizontalLayout_10.addWidget(self.tab_d_10_lb)
        self.tab_d_mzstart_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.tab_d_mzstart_dspb.setDecimals(4)
        self.tab_d_mzstart_dspb.setMaximum(5000.0)
        self.tab_d_mzstart_dspb.setProperty("value", 350.0)
        self.tab_d_mzstart_dspb.setObjectName("tab_d_mzstart_dspb")
        self.horizontalLayout_10.addWidget(self.tab_d_mzstart_dspb)
        self.tab_d_11_lb = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_11_lb.setObjectName("tab_d_11_lb")
        self.horizontalLayout_10.addWidget(self.tab_d_11_lb)
        self.tab_d_mzend_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.tab_d_mzend_dspb.setDecimals(4)
        self.tab_d_mzend_dspb.setMaximum(9000.0)
        self.tab_d_mzend_dspb.setProperty("value", 1000.0)
        self.tab_d_mzend_dspb.setObjectName("tab_d_mzend_dspb")
        self.horizontalLayout_10.addWidget(self.tab_d_mzend_dspb)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem21)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 4, 1, 1, 1)
        self.tabframe.addTab(self.link_tab, "")
        self.logo_lb = QtGui.QLabel(self.centralwidget)
        self.logo_lb.setGeometry(QtCore.QRect(10, 540, 491, 16))
        self.logo_lb.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.logo_lb.setObjectName("logo_lb")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabframe.setCurrentIndex(0)
        self.tab_d_lipidclass_cmb.setCurrentIndex(2)
        # QtCore.QObject.connect(self.tab_a_addmzml_pb, QtCore.SIGNAL("clicked()"), self.tab_a_infiles_pte.clear)
        # QtCore.QObject.connect(self.tab_a_clearall_pb, QtCore.SIGNAL("clicked()"), self.tab_a_infiles_pte.clear)
        # QtCore.QObject.connect(self.tab_b_clearall_pb, QtCore.SIGNAL("clicked()"), self.tab_b_infiles_pte.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "mzMLextractor (beta) | University of Leipzig ", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_savexlsxfolder_pb.setText(QtGui.QApplication.translate("MainWindow", "Save to folder", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_7_lb.setText(QtGui.QApplication.translate("MainWindow", "Merge to CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_clearall_pb.setText(QtGui.QApplication.translate("MainWindow", "Clear all", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_addmzml_pb.setText(QtGui.QApplication.translate("MainWindow", "Add single file", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_3_lb.setText(QtGui.QApplication.translate("MainWindow", "Add folder", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_addmzmlfolder_pb.setText(QtGui.QApplication.translate("MainWindow", "Select a folder", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_10_lb.setText(QtGui.QApplication.translate("MainWindow", "m/z range:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_11_lb.setText(QtGui.QApplication.translate("MainWindow", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_5_lb.setText(QtGui.QApplication.translate("MainWindow", "Output as Excel", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_2_lb.setText(QtGui.QApplication.translate("MainWindow", "Input .mzML file:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_runextractor_pb.setText(QtGui.QApplication.translate("MainWindow", "Run Extract", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_savecsv_pb.setText(QtGui.QApplication.translate("MainWindow", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_1_lb.setText(QtGui.QApplication.translate("MainWindow", "Step 1", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_6_lb.setText(QtGui.QApplication.translate("MainWindow", "Step 2", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_runmerge_pb.setText(QtGui.QApplication.translate("MainWindow", "Run Merge", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_8_lb.setText(QtGui.QApplication.translate("MainWindow", "rt range (min):", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_9_lb.setText(QtGui.QApplication.translate("MainWindow", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_4_lb.setText(QtGui.QApplication.translate("MainWindow", "MS level threshold(absolute):", None, QtGui.QApplication.UnicodeUTF8))
        self.tabframe.setTabText(self.tabframe.indexOf(self.extract_ms_level_tab), QtGui.QApplication.translate("MainWindow", "1. Extract MS level", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_clearall_pb.setText(QtGui.QApplication.translate("MainWindow", "Clear all", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_3_lb.setText(QtGui.QApplication.translate("MainWindow", "MS level threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_4_lb.setText(QtGui.QApplication.translate("MainWindow", "MS2 Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_1_lb.setText(QtGui.QApplication.translate("MainWindow", "Input .mzML file:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_savexlsxfolder_pb.setText(QtGui.QApplication.translate("MainWindow", "Save to folder", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_5_lb.setText(QtGui.QApplication.translate("MainWindow", "Output as Excel", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_runextract_pb.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_addmzml_pb.setText(QtGui.QApplication.translate("MainWindow", "Add single file", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_2_lb.setText(QtGui.QApplication.translate("MainWindow", "Add folder", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_addmzmlfolder_pb.setText(QtGui.QApplication.translate("MainWindow", "Select a folder", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_8_lb.setText(QtGui.QApplication.translate("MainWindow", "rt range (min):", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_11_lb.setText(QtGui.QApplication.translate("MainWindow", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_10_lb.setText(QtGui.QApplication.translate("MainWindow", "m/z range:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_9_lb.setText(QtGui.QApplication.translate("MainWindow", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.tabframe.setTabText(self.tabframe.indexOf(self.scan_info_tab), QtGui.QApplication.translate("MainWindow", "2. Extract Scan info", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_c_5_lb.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><a href=\"http://www.lipidmaps.org/tools/ms/glycerolipids_batch_bulk.html\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.lipidmaps.org/tools/ms/glycerolipids_batch_bulk.html</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_c_4_lb.setText(QtGui.QApplication.translate("MainWindow", "For Triacylglycerols:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_c_2_lb.setText(QtGui.QApplication.translate("MainWindow", "For Glycerol phospholipids:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_c_1_lb.setText(QtGui.QApplication.translate("MainWindow", "Search on LipidMaps", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_c_3_lb.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><a href=\"http://www.lipidmaps.org/tools/ms/glycerophospholipids_batch_bulk.html\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.lipidmaps.org/tools/ms/glycerophospholipids_batch_bulk.html</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabframe.setTabText(self.tabframe.indexOf(self.search_tab), QtGui.QApplication.translate("MainWindow", "3. Bulk Search", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_lipidclass_cmb.setItemText(0, QtGui.QApplication.translate("MainWindow", "Phosphatidic acid (PA) [M-H]-", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_lipidclass_cmb.setItemText(1, QtGui.QApplication.translate("MainWindow", "Phosphatidylethanolamine (PE) [M-H]-", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_lipidclass_cmb.setItemText(2, QtGui.QApplication.translate("MainWindow", "Phosphatidylcholine (PC) [M+HCOO]-", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_lipidclass_cmb.setItemText(3, QtGui.QApplication.translate("MainWindow", "Phosphatidylglycerol (PG) [M-H]-", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_lipidclass_cmb.setItemText(4, QtGui.QApplication.translate("MainWindow", "Phosphatidylserine (PS) [M-H]-", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_lipidclass_cmb.setItemText(5, QtGui.QApplication.translate("MainWindow", "Phosphatidylinositol (PI) [M-H]-", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_lipidclass_cmb.setItemText(6, QtGui.QApplication.translate("MainWindow", "Triacylglycerol (TG) [M+H]+", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_lipidclass_cmb.setItemText(7, QtGui.QApplication.translate("MainWindow", "Triacylglycerol (TG) [M+NH4]+", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_runextract_pb.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_4_lb.setText(QtGui.QApplication.translate("MainWindow", "Hole spectra .mzML", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_ms2mzml_pb.setText(QtGui.QApplication.translate("MainWindow", "Select file", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_lipidstable_pb.setText(QtGui.QApplication.translate("MainWindow", "Select file", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_2_lb.setText(QtGui.QApplication.translate("MainWindow", "Bulk search result", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_5_lb.setText(QtGui.QApplication.translate("MainWindow", "MS level threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_6_lb.setText(QtGui.QApplication.translate("MainWindow", "MS2 Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_7_lb.setText(QtGui.QApplication.translate("MainWindow", "Output as Excel", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_1_lb.setText(QtGui.QApplication.translate("MainWindow", "Select lipid class", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_xlsxpath_pb.setText(QtGui.QApplication.translate("MainWindow", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_msmzml_pb.setText(QtGui.QApplication.translate("MainWindow", "Select file", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_3_lb.setText(QtGui.QApplication.translate("MainWindow", "MS only .mzML", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_8_lb.setText(QtGui.QApplication.translate("MainWindow", "rt range (min):", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_9_lb.setText(QtGui.QApplication.translate("MainWindow", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_10_lb.setText(QtGui.QApplication.translate("MainWindow", "m/z range:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_11_lb.setText(QtGui.QApplication.translate("MainWindow", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.tabframe.setTabText(self.tabframe.indexOf(self.link_tab), QtGui.QApplication.translate("MainWindow", "4. Link lipids to scans", None, QtGui.QApplication.UnicodeUTF8))
        self.logo_lb.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>mzMLextractor (c) 2016 | <a href=\"http://www.zv.uni-leipzig.de/\"><span style=\" text-decoration: underline; color:#0000ff;\">University of Leipzig</span></a> | <a href=\"http://research.uni-leipzig.de/bioanalytik/\"><span style=\" text-decoration: underline; color:#0000ff;\">AG Bioanalytik</span></a> | <a href=\"https://home.uni-leipzig.de/fedorova/\"><span style=\" text-decoration: underline; color:#0000ff;\">Fedorova Research Group</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

