# -*- coding: utf-8 -*-
#
# Copyright (C) 2016-2017  SysMedOs_team @ AG Bioanalytik, University of Leipzig:
# SysMedOs_team: Zhixu Ni, Georgia Angelidou, Mike Lange, Maria Fedorova
# LipidHunter is Dual-licensed
#     For academic and non-commercial use: `GPLv2 License` Please read more information by the following link:
#         [The GNU General Public License version 2] (https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html)
#     For commercial use:
#         please contact the SysMedOs_team by email.
# Please cite our publication in an appropriate form.
# Ni, Zhixu, Georgia Angelidou, Mike Lange, Ralf Hoffmann, and Maria Fedorova.
# "LipidHunter identifies phospholipids by high-throughput processing of LC-MS and shotgun lipidomics datasets."
# Analytical Chemistry (2017).
# DOI: 10.1021/acs.analchem.7b01126
#
# For more info please contact:
#     SysMedOs_team: oxlpp@bbz.uni-leipzig.de
#     Developer Zhixu Ni zhixu.ni@uni-leipzig.de
#     Developer Georgia Angelidou georgia.angelidou@uni-leipzig.de

# Form implementation generated from reading ui file '.\BatchHunter_UI.ui'
#
# Created: Fri Mar 17 00:09:48 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 720)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/LipidHunter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabframe = QtGui.QTabWidget(self.centralwidget)
        self.tabframe.setGeometry(QtCore.QRect(10, 10, 931, 631))
        self.tabframe.setObjectName("tabframe")
        self.scan_info_tab = QtGui.QWidget()
        self.scan_info_tab.setObjectName("scan_info_tab")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.scan_info_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 901, 581))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.tab_a_clearall_pb = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.tab_a_clearall_pb.setObjectName("tab_a_clearall_pb")
        self.verticalLayout_2.addWidget(self.tab_a_clearall_pb)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 2, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tab_b_3_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_3_lb.setObjectName("tab_b_3_lb")
        self.horizontalLayout_4.addWidget(self.tab_b_3_lb)
        self.tab_a_maxbatch_spb = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.tab_a_maxbatch_spb.setMaximum(16)
        self.tab_a_maxbatch_spb.setProperty("value", 3)
        self.tab_a_maxbatch_spb.setObjectName("tab_a_maxbatch_spb")
        self.horizontalLayout_4.addWidget(self.tab_a_maxbatch_spb)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.tab_b_4_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_4_lb.setObjectName("tab_b_4_lb")
        self.horizontalLayout_4.addWidget(self.tab_b_4_lb)
        self.tab_a_maxsubcore_spb = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.tab_a_maxsubcore_spb.setMaximum(16)
        self.tab_a_maxsubcore_spb.setProperty("value", 1)
        self.tab_a_maxsubcore_spb.setObjectName("tab_a_maxsubcore_spb")
        self.horizontalLayout_4.addWidget(self.tab_a_maxsubcore_spb)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.tab_b_6_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_6_lb.setObjectName("tab_b_6_lb")
        self.horizontalLayout_4.addWidget(self.tab_b_6_lb)
        self.tab_a_maxsubram_spb = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.tab_a_maxsubram_spb.setMinimum(1)
        self.tab_a_maxsubram_spb.setMaximum(64)
        self.tab_a_maxsubram_spb.setProperty("value", 2)
        self.tab_a_maxsubram_spb.setObjectName("tab_a_maxsubram_spb")
        self.horizontalLayout_4.addWidget(self.tab_a_maxsubram_spb)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 1, 1, 1)
        self.tab_a_runbatch_pb = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.tab_a_runbatch_pb.setObjectName("tab_a_runbatch_pb")
        self.gridLayout_2.addWidget(self.tab_a_runbatch_pb, 5, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 4, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tab_b_1_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_1_lb.setObjectName("tab_b_1_lb")
        self.horizontalLayout_3.addWidget(self.tab_b_1_lb)
        self.tab_a_addcfg_pb = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.tab_a_addcfg_pb.setObjectName("tab_a_addcfg_pb")
        self.horizontalLayout_3.addWidget(self.tab_a_addcfg_pb)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.tab_b_2_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_2_lb.setObjectName("tab_b_2_lb")
        self.horizontalLayout_3.addWidget(self.tab_b_2_lb)
        self.tab_a_addcfgfolder_pb = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.tab_a_addcfgfolder_pb.setObjectName("tab_a_addcfgfolder_pb")
        self.horizontalLayout_3.addWidget(self.tab_a_addcfgfolder_pb)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.tab_b_infiles_pte = QtGui.QPlainTextEdit(self.gridLayoutWidget_2)
        self.tab_b_infiles_pte.setObjectName("tab_b_infiles_pte")
        self.gridLayout_2.addWidget(self.tab_b_infiles_pte, 1, 1, 1, 1)
        self.tab_b_statusrun_pte = QtGui.QPlainTextEdit(self.gridLayoutWidget_2)
        self.tab_b_statusrun_pte.setMaximumSize(QtCore.QSize(16777215, 400))
        self.tab_b_statusrun_pte.setObjectName("tab_b_statusrun_pte")
        self.gridLayout_2.addWidget(self.tab_b_statusrun_pte, 5, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.tabframe.addTab(self.scan_info_tab, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtGui.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 0, 731, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_25 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_4.addWidget(self.label_25)
        self.label_26 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_4.addWidget(self.label_26)
        self.label_43 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_4.addWidget(self.label_43)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_42 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_42.setObjectName("label_42")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_42)
        self.label_44 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_44.setObjectName("label_44")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_44)
        self.label_27 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_27.setObjectName("label_27")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_27)
        self.label_45 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_45.setTextFormat(QtCore.Qt.RichText)
        self.label_45.setObjectName("label_45")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_45)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.label_28 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_4.addWidget(self.label_28)
        self.label_29 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_4.addWidget(self.label_29)
        self.label_37 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_4.addWidget(self.label_37)
        self.line_8 = QtGui.QFrame(self.tab)
        self.line_8.setGeometry(QtCore.QRect(10, 170, 901, 16))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_30 = QtGui.QLabel(self.tab)
        self.label_30.setGeometry(QtCore.QRect(20, 180, 881, 16))
        self.label_30.setObjectName("label_30")
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 128, 128))
        self.pushButton.setMinimumSize(QtCore.QSize(128, 128))
        self.pushButton.setMaximumSize(QtCore.QSize(128, 128))
        self.pushButton.setText("")
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(128, 128))
        self.pushButton.setObjectName("pushButton")
        self.formLayoutWidget_3 = QtGui.QWidget(self.tab)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(20, 210, 881, 241))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_31 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_31.setObjectName("label_31")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_31)
        self.label_50 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_50.setObjectName("label_50")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_50)
        self.label_36 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_36.setObjectName("label_36")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_36)
        self.label_55 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_55.setMinimumSize(QtCore.QSize(0, 15))
        self.label_55.setMaximumSize(QtCore.QSize(800, 16777215))
        self.label_55.setTextFormat(QtCore.Qt.RichText)
        self.label_55.setWordWrap(True)
        self.label_55.setObjectName("label_55")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_55)
        self.label_32 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_32.setObjectName("label_32")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_32)
        self.label_48 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_48.setObjectName("label_48")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_48)
        self.label_33 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_33.setObjectName("label_33")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_33)
        self.label_53 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_53.setMinimumSize(QtCore.QSize(0, 15))
        self.label_53.setMaximumSize(QtCore.QSize(800, 16777215))
        self.label_53.setTextFormat(QtCore.Qt.RichText)
        self.label_53.setWordWrap(True)
        self.label_53.setObjectName("label_53")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.label_53)
        self.label_34 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_34.setObjectName("label_34")
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_34)
        self.label_51 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_51.setObjectName("label_51")
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.label_51)
        self.line_10 = QtGui.QFrame(self.tab)
        self.line_10.setGeometry(QtCore.QRect(10, 450, 901, 16))
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.label_46 = QtGui.QLabel(self.tab)
        self.label_46.setGeometry(QtCore.QRect(20, 460, 881, 16))
        self.label_46.setObjectName("label_46")
        self.formLayoutWidget_2 = QtGui.QWidget(self.tab)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 482, 881, 71))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_47 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_47.setObjectName("label_47")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_47)
        self.label_49 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_49.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_49.setObjectName("label_49")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_49)
        self.label_52 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_52.setObjectName("label_52")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_52)
        self.label_56 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_56.setObjectName("label_56")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_56)
        self.label_57 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_57.setObjectName("label_57")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_57)
        self.label_58 = QtGui.QLabel(self.formLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_58.sizePolicy().hasHeightForWidth())
        self.label_58.setSizePolicy(sizePolicy)
        self.label_58.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_58.setObjectName("label_58")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_58)
        self.tabframe.addTab(self.tab, "")
        self.logo_lb = QtGui.QLabel(self.centralwidget)
        self.logo_lb.setGeometry(QtCore.QRect(20, 650, 901, 16))
        self.logo_lb.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.logo_lb.setObjectName("logo_lb")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabframe.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "LipidHunter Batch Mode (beta) | University of Leipzig ", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_clearall_pb.setText(QtGui.QApplication.translate("MainWindow", "Clear all", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_3_lb.setText(QtGui.QApplication.translate("MainWindow", "Max number of files in parallel:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_4_lb.setText(QtGui.QApplication.translate("MainWindow", "Max cores for each file", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_6_lb.setText(QtGui.QApplication.translate("MainWindow", "Max RAM for each file", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_maxsubram_spb.setSuffix(QtGui.QApplication.translate("MainWindow", " GB", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_runbatch_pb.setText(QtGui.QApplication.translate("MainWindow", "Run Batch Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_1_lb.setText(QtGui.QApplication.translate("MainWindow", "Input batch settings file:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_addcfg_pb.setText(QtGui.QApplication.translate("MainWindow", "Add single file", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_2_lb.setText(QtGui.QApplication.translate("MainWindow", "Add all batch settings in a folder", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_addcfgfolder_pb.setText(QtGui.QApplication.translate("MainWindow", "Select a folder", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Load batch settings files:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Parallelization settings:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabframe.setTabText(self.tabframe.indexOf(self.scan_info_tab), QtGui.QApplication.translate("MainWindow", "LipidHunter Batch Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "LipidHunter Beta relased date: 16, March, 2017", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Developed by: SysMedOs team", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">LipidHunter is Dual-Licensed:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("MainWindow", "       For academic & non-commercial use:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("MainWindow", "       For commercial use please contact the developers:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Under GPL v2 License: <a href=\" https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html\"><span style=\" text-decoration: none; color:    #FF8C00;\">https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>oxlpp@bbz.uni-leipzig.de</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Project page: <a href=\" https://bitbucket.org/SysMedOs/lipidhunter\"><span style=\" text-decoration: none; color:#ff8c00;\">https://bitbucket.org/SysMedOs/lipidhunter</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Online tutorial: <a href=\"https://bitbucket.org/SysMedOs/lipidhunter/wiki/\"><span style=\" text-decoration: none; color:#FF8C00;\">https://bitbucket.org/SysMedOs/lipidhunter/wiki/</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "Please cite our publication:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "We acknowlege all open source libraries used in LipidHunter:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "matplotlib", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><a href=\"http://www.matplotlib.org\"><span style=\"  text-decoration: none; color:#FF8C00;\">http://www.matplotlib.org</span></a><br/>John D. Hunter. Matplotlib: A 2D Graphics Environment,<br/>Computing in Science &amp; Engineering, 9, 90-95 (2007), DOI:10.1109/MCSE.2007.55 </p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "numpy & scipy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><a href=\"https://www.numpy.org\"><span style=\" color:#ff8c00;\">https://www.numpy.org</span></a> &amp; <a href=\"https://www.scipy.org\"><span style=\" text-decoration: underline; color:#ff8c00;\">https://www.scipy.org</span></a><br/>Stéfan van der Walt, S. Chris Colbert and Gaël Varoquaux. The NumPy Array: A Structure for Efficient Numerical Computation, <br/>Computing in Science &amp; Engineering, 13, 22-30 (2011), DOI:10.1109/MCSE.2011.37 </p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "pandas", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><a href=\"http://pandas.pydata.org\"><span style=\"  text-decoration: none; color:#FF8C00;\">http://pandas.pydata.org</span></a><br/>Wes McKinney. Data Structures for Statistical Computing in Python,<br/>Proceedings of the 9th Python in Science Conference, 51-56 (2010) </p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "pymzML", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><a href=\"https://pymzml.github.io\"><span style=\" color:#ff8c00;\">https://pymzml.github.io</span></a><br/>Bald, T., Barth, J., Niehues, A., Specht, M., Hippler, M., and Fufezan, C. (2012) <br/>pymzML - Python module for high throughput bioinformatics on mass spectrometry data,<br/>Bioinformatics, DOI: 10.1093/bioinformatics/bts066 </p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "pyside", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><a href=\"https://wiki.qt.io/PySide\"><span style=\"  text-decoration: none; color:#FF8C00;\">https://wiki.qt.io/PySide</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("MainWindow", "We acknowlege all projects that supports the development of LipidHunter:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("MainWindow", "BMBF - Federal Ministry of Education and Research Germany:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("MainWindow", "e:Med Systems Medicine Network:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><a href=\"https://www.bmbf.de/en/\"><span style=\"  text-decoration: none; color:#FF8C00;\">https://www.bmbf.de/en/</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><a href=\"http://www.sys-med.de/en/\"><span style=\"   text-decoration: none; color:#FF8C00;\">http://www.sys-med.de/en/</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><a href=\"https://home.uni-leipzig.de/fedorova/sysmedos/\"><span style=\"   text-decoration: none; color:#FF8C00;\">https://home.uni-leipzig.de/fedorova/sysmedos/</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("MainWindow", "SysMedOS Project : ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabframe.setTabText(self.tabframe.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "About LipidHunter Batch Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.logo_lb.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>LipidHunter Batch Mode (C) 2016-2017 | <a href=\"http://www.zv.uni-leipzig.de/\"><span style=\" text-decoration: none; color:#FF8C00;\">University of Leipzig</span></a> | <a href=\"http://research.uni-leipzig.de/bioanalytik/\"><span style=\"  text-decoration: none; color:#FF8C00;\">AG Bioanalytik</span></a> | <a href=\"https://home.uni-leipzig.de/fedorova/\"><span style=\"  text-decoration: none; color:#FF8C00;\">Fedorova Research Group</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

import LipidHunter_rcc
