# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\LipidHunter_UI.ui'
#
# Created: Wed Jan 18 10:43:59 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/LipidHunter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabframe = QtGui.QTabWidget(self.centralwidget)
        self.tabframe.setGeometry(QtCore.QRect(10, 40, 781, 491))
        self.tabframe.setObjectName("tabframe")
        self.extract_ms_level_tab = QtGui.QWidget()
        self.extract_ms_level_tab.setObjectName("extract_ms_level_tab")
        self.gridLayoutWidget = QtGui.QWidget(self.extract_ms_level_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 751, 461))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tab_a_savexlsxfolder_pb = QtGui.QPushButton(self.gridLayoutWidget)
        self.tab_a_savexlsxfolder_pb.setObjectName("tab_a_savexlsxfolder_pb")
        self.gridLayout.addWidget(self.tab_a_savexlsxfolder_pb, 5, 2, 1, 1)
        self.tab_a_statusextractor_pte = QtGui.QPlainTextEdit(self.gridLayoutWidget)
        self.tab_a_statusextractor_pte.setMinimumSize(QtCore.QSize(0, 40))
        self.tab_a_statusextractor_pte.setMaximumSize(QtCore.QSize(16777215, 150))
        self.tab_a_statusextractor_pte.setObjectName("tab_a_statusextractor_pte")
        self.gridLayout.addWidget(self.tab_a_statusextractor_pte, 6, 1, 1, 1)
        self.tab_a_statusmerger_pte = QtGui.QPlainTextEdit(self.gridLayoutWidget)
        self.tab_a_statusmerger_pte.setMinimumSize(QtCore.QSize(0, 50))
        self.tab_a_statusmerger_pte.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tab_a_statusmerger_pte.setObjectName("tab_a_statusmerger_pte")
        self.gridLayout.addWidget(self.tab_a_statusmerger_pte, 9, 1, 1, 1)
        self.tab_a_csvfolder_le = QtGui.QLineEdit(self.gridLayoutWidget)
        self.tab_a_csvfolder_le.setObjectName("tab_a_csvfolder_le")
        self.gridLayout.addWidget(self.tab_a_csvfolder_le, 8, 1, 1, 1)
        self.tab_a_7_lb = QtGui.QLabel(self.gridLayoutWidget)
        self.tab_a_7_lb.setObjectName("tab_a_7_lb")
        self.gridLayout.addWidget(self.tab_a_7_lb, 8, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tab_a_clearall_pb = QtGui.QPushButton(self.gridLayoutWidget)
        self.tab_a_clearall_pb.setObjectName("tab_a_clearall_pb")
        self.verticalLayout.addWidget(self.tab_a_clearall_pb)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout, 2, 2, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tab_a_addmzml_pb = QtGui.QPushButton(self.gridLayoutWidget)
        self.tab_a_addmzml_pb.setObjectName("tab_a_addmzml_pb")
        self.horizontalLayout_2.addWidget(self.tab_a_addmzml_pb)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.tab_a_3_lb = QtGui.QLabel(self.gridLayoutWidget)
        self.tab_a_3_lb.setObjectName("tab_a_3_lb")
        self.horizontalLayout_2.addWidget(self.tab_a_3_lb)
        self.tab_a_addmzmlfolder_pb = QtGui.QPushButton(self.gridLayoutWidget)
        self.tab_a_addmzmlfolder_pb.setObjectName("tab_a_addmzmlfolder_pb")
        self.horizontalLayout_2.addWidget(self.tab_a_addmzmlfolder_pb)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tab_a_10_lb = QtGui.QLabel(self.gridLayoutWidget)
        self.tab_a_10_lb.setObjectName("tab_a_10_lb")
        self.horizontalLayout.addWidget(self.tab_a_10_lb)
        self.tab_a_mzstart_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.tab_a_mzstart_dspb.setDecimals(4)
        self.tab_a_mzstart_dspb.setMaximum(5000.0)
        self.tab_a_mzstart_dspb.setProperty("value", 350.0)
        self.tab_a_mzstart_dspb.setObjectName("tab_a_mzstart_dspb")
        self.horizontalLayout.addWidget(self.tab_a_mzstart_dspb)
        self.tab_a_11_lb = QtGui.QLabel(self.gridLayoutWidget)
        self.tab_a_11_lb.setObjectName("tab_a_11_lb")
        self.horizontalLayout.addWidget(self.tab_a_11_lb)
        self.tab_a_mzend_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.tab_a_mzend_dspb.setDecimals(4)
        self.tab_a_mzend_dspb.setMaximum(9000.0)
        self.tab_a_mzend_dspb.setProperty("value", 1000.0)
        self.tab_a_mzend_dspb.setObjectName("tab_a_mzend_dspb")
        self.horizontalLayout.addWidget(self.tab_a_mzend_dspb)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 1, 1, 1)
        self.tab_a_5_lb = QtGui.QLabel(self.gridLayoutWidget)
        self.tab_a_5_lb.setObjectName("tab_a_5_lb")
        self.gridLayout.addWidget(self.tab_a_5_lb, 5, 0, 1, 1)
        self.tab_a_2_lb = QtGui.QLabel(self.gridLayoutWidget)
        self.tab_a_2_lb.setObjectName("tab_a_2_lb")
        self.gridLayout.addWidget(self.tab_a_2_lb, 1, 0, 1, 1)
        self.tab_a_runextractor_pb = QtGui.QPushButton(self.gridLayoutWidget)
        self.tab_a_runextractor_pb.setObjectName("tab_a_runextractor_pb")
        self.gridLayout.addWidget(self.tab_a_runextractor_pb, 6, 0, 1, 1)
        self.tab_a_savecsv_pb = QtGui.QPushButton(self.gridLayoutWidget)
        self.tab_a_savecsv_pb.setObjectName("tab_a_savecsv_pb")
        self.gridLayout.addWidget(self.tab_a_savecsv_pb, 8, 2, 1, 1)
        self.tab_a_xlsxfolder_le = QtGui.QLineEdit(self.gridLayoutWidget)
        self.tab_a_xlsxfolder_le.setObjectName("tab_a_xlsxfolder_le")
        self.gridLayout.addWidget(self.tab_a_xlsxfolder_le, 5, 1, 1, 1)
        self.tab_a_infiles_pte = QtGui.QPlainTextEdit(self.gridLayoutWidget)
        self.tab_a_infiles_pte.setMinimumSize(QtCore.QSize(0, 50))
        self.tab_a_infiles_pte.setMaximumSize(QtCore.QSize(16777215, 150))
        self.tab_a_infiles_pte.setObjectName("tab_a_infiles_pte")
        self.gridLayout.addWidget(self.tab_a_infiles_pte, 2, 1, 1, 1)
        self.tab_a_1_lb = QtGui.QLabel(self.gridLayoutWidget)
        self.tab_a_1_lb.setObjectName("tab_a_1_lb")
        self.gridLayout.addWidget(self.tab_a_1_lb, 0, 1, 1, 1)
        self.tab_a_6_lb = QtGui.QLabel(self.gridLayoutWidget)
        self.tab_a_6_lb.setObjectName("tab_a_6_lb")
        self.gridLayout.addWidget(self.tab_a_6_lb, 7, 1, 1, 1)
        self.tab_a_runmerge_pb = QtGui.QPushButton(self.gridLayoutWidget)
        self.tab_a_runmerge_pb.setObjectName("tab_a_runmerge_pb")
        self.gridLayout.addWidget(self.tab_a_runmerge_pb, 9, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tab_a_8_lb = QtGui.QLabel(self.gridLayoutWidget)
        self.tab_a_8_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tab_a_8_lb.setObjectName("tab_a_8_lb")
        self.horizontalLayout_8.addWidget(self.tab_a_8_lb)
        self.tab_a_rtstart_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.tab_a_rtstart_dspb.setMaximum(300.0)
        self.tab_a_rtstart_dspb.setSingleStep(1.0)
        self.tab_a_rtstart_dspb.setProperty("value", 3.0)
        self.tab_a_rtstart_dspb.setObjectName("tab_a_rtstart_dspb")
        self.horizontalLayout_8.addWidget(self.tab_a_rtstart_dspb)
        self.tab_a_9_lb = QtGui.QLabel(self.gridLayoutWidget)
        self.tab_a_9_lb.setObjectName("tab_a_9_lb")
        self.horizontalLayout_8.addWidget(self.tab_a_9_lb)
        self.tab_a_rtend_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.tab_a_rtend_dspb.setMaximum(300.0)
        self.tab_a_rtend_dspb.setProperty("value", 20.0)
        self.tab_a_rtend_dspb.setObjectName("tab_a_rtend_dspb")
        self.horizontalLayout_8.addWidget(self.tab_a_rtend_dspb)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.tab_a_4_lb = QtGui.QLabel(self.gridLayoutWidget)
        self.tab_a_4_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tab_a_4_lb.setObjectName("tab_a_4_lb")
        self.horizontalLayout_8.addWidget(self.tab_a_4_lb)
        self.tab_a_msthreshold_spb = QtGui.QSpinBox(self.gridLayoutWidget)
        self.tab_a_msthreshold_spb.setMaximum(1000000000)
        self.tab_a_msthreshold_spb.setProperty("value", 1000)
        self.tab_a_msthreshold_spb.setObjectName("tab_a_msthreshold_spb")
        self.horizontalLayout_8.addWidget(self.tab_a_msthreshold_spb)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_8, 3, 1, 1, 1)
        self.tabframe.addTab(self.extract_ms_level_tab, "")
        self.scan_info_tab = QtGui.QWidget()
        self.scan_info_tab.setObjectName("scan_info_tab")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.scan_info_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 751, 421))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.tab_b_clearall_pb = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.tab_b_clearall_pb.setObjectName("tab_b_clearall_pb")
        self.verticalLayout_2.addWidget(self.tab_b_clearall_pb)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 2, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tab_b_3_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_3_lb.setObjectName("tab_b_3_lb")
        self.horizontalLayout_4.addWidget(self.tab_b_3_lb)
        self.tab_b_msthreshold_spb = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.tab_b_msthreshold_spb.setMaximum(999999)
        self.tab_b_msthreshold_spb.setProperty("value", 1000)
        self.tab_b_msthreshold_spb.setObjectName("tab_b_msthreshold_spb")
        self.horizontalLayout_4.addWidget(self.tab_b_msthreshold_spb)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.tab_b_4_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_4_lb.setObjectName("tab_b_4_lb")
        self.horizontalLayout_4.addWidget(self.tab_b_4_lb)
        self.tab_b_ms2threshold_spb = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.tab_b_ms2threshold_spb.setMaximum(99999)
        self.tab_b_ms2threshold_spb.setProperty("value", 10)
        self.tab_b_ms2threshold_spb.setObjectName("tab_b_ms2threshold_spb")
        self.horizontalLayout_4.addWidget(self.tab_b_ms2threshold_spb)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.tab_b_6_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_6_lb.setObjectName("tab_b_6_lb")
        self.horizontalLayout_4.addWidget(self.tab_b_6_lb)
        self.tab_b_dda_spb = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.tab_b_dda_spb.setMinimum(1)
        self.tab_b_dda_spb.setMaximum(20)
        self.tab_b_dda_spb.setProperty("value", 6)
        self.tab_b_dda_spb.setObjectName("tab_b_dda_spb")
        self.horizontalLayout_4.addWidget(self.tab_b_dda_spb)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 4, 1, 1, 1)
        self.tab_b_1_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_1_lb.setObjectName("tab_b_1_lb")
        self.gridLayout_2.addWidget(self.tab_b_1_lb, 0, 0, 1, 1)
        self.tab_b_savexlsxfolder_pb = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.tab_b_savexlsxfolder_pb.setObjectName("tab_b_savexlsxfolder_pb")
        self.gridLayout_2.addWidget(self.tab_b_savexlsxfolder_pb, 6, 2, 1, 1)
        self.tab_b_outpufolder_le = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.tab_b_outpufolder_le.setObjectName("tab_b_outpufolder_le")
        self.gridLayout_2.addWidget(self.tab_b_outpufolder_le, 6, 1, 1, 1)
        self.tab_b_5_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_5_lb.setObjectName("tab_b_5_lb")
        self.gridLayout_2.addWidget(self.tab_b_5_lb, 6, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 5, 1, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 7, 1, 1, 1)
        self.tab_b_runextract_pb = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.tab_b_runextract_pb.setObjectName("tab_b_runextract_pb")
        self.gridLayout_2.addWidget(self.tab_b_runextract_pb, 8, 0, 1, 1)
        self.tab_b_infiles_pte = QtGui.QPlainTextEdit(self.gridLayoutWidget_2)
        self.tab_b_infiles_pte.setObjectName("tab_b_infiles_pte")
        self.gridLayout_2.addWidget(self.tab_b_infiles_pte, 1, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tab_b_addmzml_pb = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.tab_b_addmzml_pb.setObjectName("tab_b_addmzml_pb")
        self.horizontalLayout_3.addWidget(self.tab_b_addmzml_pb)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem13)
        self.tab_b_2_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_2_lb.setObjectName("tab_b_2_lb")
        self.horizontalLayout_3.addWidget(self.tab_b_2_lb)
        self.tab_b_addmzmlfolder_pb = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.tab_b_addmzmlfolder_pb.setObjectName("tab_b_addmzmlfolder_pb")
        self.horizontalLayout_3.addWidget(self.tab_b_addmzmlfolder_pb)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.tab_b_statusrun_pte = QtGui.QPlainTextEdit(self.gridLayoutWidget_2)
        self.tab_b_statusrun_pte.setMaximumSize(QtCore.QSize(16777215, 200))
        self.tab_b_statusrun_pte.setObjectName("tab_b_statusrun_pte")
        self.gridLayout_2.addWidget(self.tab_b_statusrun_pte, 8, 1, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tab_b_8_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_8_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tab_b_8_lb.setObjectName("tab_b_8_lb")
        self.horizontalLayout_9.addWidget(self.tab_b_8_lb)
        self.tab_b_rtstart_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.tab_b_rtstart_dspb.setMaximum(300.0)
        self.tab_b_rtstart_dspb.setSingleStep(1.0)
        self.tab_b_rtstart_dspb.setProperty("value", 3.0)
        self.tab_b_rtstart_dspb.setObjectName("tab_b_rtstart_dspb")
        self.horizontalLayout_9.addWidget(self.tab_b_rtstart_dspb)
        self.tab_b_11_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_11_lb.setObjectName("tab_b_11_lb")
        self.horizontalLayout_9.addWidget(self.tab_b_11_lb)
        self.tab_b_rtend_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.tab_b_rtend_dspb.setMaximum(300.0)
        self.tab_b_rtend_dspb.setProperty("value", 20.0)
        self.tab_b_rtend_dspb.setObjectName("tab_b_rtend_dspb")
        self.horizontalLayout_9.addWidget(self.tab_b_rtend_dspb)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem14)
        self.tab_b_10_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_10_lb.setObjectName("tab_b_10_lb")
        self.horizontalLayout_9.addWidget(self.tab_b_10_lb)
        self.tab_b_mzstart_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.tab_b_mzstart_dspb.setDecimals(4)
        self.tab_b_mzstart_dspb.setMaximum(5000.0)
        self.tab_b_mzstart_dspb.setProperty("value", 350.0)
        self.tab_b_mzstart_dspb.setObjectName("tab_b_mzstart_dspb")
        self.horizontalLayout_9.addWidget(self.tab_b_mzstart_dspb)
        self.tab_b_9_lb = QtGui.QLabel(self.gridLayoutWidget_2)
        self.tab_b_9_lb.setObjectName("tab_b_9_lb")
        self.horizontalLayout_9.addWidget(self.tab_b_9_lb)
        self.tab_b_mzend_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.tab_b_mzend_dspb.setDecimals(4)
        self.tab_b_mzend_dspb.setMaximum(9000.0)
        self.tab_b_mzend_dspb.setProperty("value", 1000.0)
        self.tab_b_mzend_dspb.setObjectName("tab_b_mzend_dspb")
        self.horizontalLayout_9.addWidget(self.tab_b_mzend_dspb)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem15)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 9, 1, 1, 1)
        self.tabframe.addTab(self.scan_info_tab, "")
        self.search_tab = QtGui.QWidget()
        self.search_tab.setObjectName("search_tab")
        self.gridLayoutWidget_4 = QtGui.QWidget(self.search_tab)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 751, 131))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tab_c_5_lb = QtGui.QLabel(self.gridLayoutWidget_4)
        self.tab_c_5_lb.setTextFormat(QtCore.Qt.RichText)
        self.tab_c_5_lb.setObjectName("tab_c_5_lb")
        self.gridLayout_4.addWidget(self.tab_c_5_lb, 6, 1, 1, 1)
        self.tab_c_1_lb = QtGui.QLabel(self.gridLayoutWidget_4)
        self.tab_c_1_lb.setObjectName("tab_c_1_lb")
        self.gridLayout_4.addWidget(self.tab_c_1_lb, 0, 1, 1, 1)
        self.tab_c_2_lb = QtGui.QLabel(self.gridLayoutWidget_4)
        self.tab_c_2_lb.setMaximumSize(QtCore.QSize(140, 16777215))
        self.tab_c_2_lb.setObjectName("tab_c_2_lb")
        self.gridLayout_4.addWidget(self.tab_c_2_lb, 2, 0, 1, 1)
        self.tab_c_4_lb = QtGui.QLabel(self.gridLayoutWidget_4)
        self.tab_c_4_lb.setObjectName("tab_c_4_lb")
        self.gridLayout_4.addWidget(self.tab_c_4_lb, 5, 0, 1, 1)
        self.tab_c_3_lb = QtGui.QLabel(self.gridLayoutWidget_4)
        self.tab_c_3_lb.setTextFormat(QtCore.Qt.RichText)
        self.tab_c_3_lb.setObjectName("tab_c_3_lb")
        self.gridLayout_4.addWidget(self.tab_c_3_lb, 3, 1, 1, 1)
        self.line = QtGui.QFrame(self.gridLayoutWidget_4)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 1, 1, 1, 1)
        self.line_2 = QtGui.QFrame(self.gridLayoutWidget_4)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 4, 1, 1, 1)
        self.line_3 = QtGui.QFrame(self.gridLayoutWidget_4)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 4, 0, 1, 1)
        self.line_4 = QtGui.QFrame(self.gridLayoutWidget_4)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_4.addWidget(self.line_4, 1, 0, 1, 1)
        self.tabframe.addTab(self.search_tab, "")
        self.link_tab = QtGui.QWidget()
        self.link_tab.setObjectName("link_tab")
        self.gridLayoutWidget_3 = QtGui.QWidget(self.link_tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 751, 441))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tab_d_4_lb = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_4_lb.setObjectName("tab_d_4_lb")
        self.gridLayout_3.addWidget(self.tab_d_4_lb, 3, 0, 1, 1)
        self.tab_d_runextract_pb = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.tab_d_runextract_pb.setObjectName("tab_d_runextract_pb")
        self.gridLayout_3.addWidget(self.tab_d_runextract_pb, 9, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tab_d_lipidclass_cmb = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.tab_d_lipidclass_cmb.setMinimumSize(QtCore.QSize(220, 0))
        self.tab_d_lipidclass_cmb.setObjectName("tab_d_lipidclass_cmb")
        self.tab_d_lipidclass_cmb.addItem("")
        self.tab_d_lipidclass_cmb.addItem("")
        self.tab_d_lipidclass_cmb.addItem("")
        self.tab_d_lipidclass_cmb.addItem("")
        self.tab_d_lipidclass_cmb.addItem("")
        self.tab_d_lipidclass_cmb.addItem("")
        self.tab_d_lipidclass_cmb.addItem("")
        self.tab_d_lipidclass_cmb.addItem("")
        self.horizontalLayout_6.addWidget(self.tab_d_lipidclass_cmb)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem16)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 0, 1, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tab_d_ms2mzml_pb = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.tab_d_ms2mzml_pb.setObjectName("tab_d_ms2mzml_pb")
        self.verticalLayout_3.addWidget(self.tab_d_ms2mzml_pb)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 3, 2, 1, 1)
        self.tab_d_lipidstable_le = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.tab_d_lipidstable_le.setObjectName("tab_d_lipidstable_le")
        self.gridLayout_3.addWidget(self.tab_d_lipidstable_le, 1, 1, 1, 1)
        self.tab_d_lipidstable_pb = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.tab_d_lipidstable_pb.setObjectName("tab_d_lipidstable_pb")
        self.gridLayout_3.addWidget(self.tab_d_lipidstable_pb, 1, 2, 1, 1)
        self.tab_d_2_lb = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_2_lb.setObjectName("tab_d_2_lb")
        self.gridLayout_3.addWidget(self.tab_d_2_lb, 1, 0, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem17, 6, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tab_d_5_lb = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_5_lb.setObjectName("tab_d_5_lb")
        self.horizontalLayout_5.addWidget(self.tab_d_5_lb)
        self.tab_d_msthreshold_spb = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.tab_d_msthreshold_spb.setMaximum(999999)
        self.tab_d_msthreshold_spb.setProperty("value", 1000)
        self.tab_d_msthreshold_spb.setObjectName("tab_d_msthreshold_spb")
        self.horizontalLayout_5.addWidget(self.tab_d_msthreshold_spb)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem18)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.doubleSpinBox.setMaximum(2.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setProperty("value", 0.75)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox)
        self.tab_d_6_lb = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_6_lb.setObjectName("tab_d_6_lb")
        self.horizontalLayout_5.addWidget(self.tab_d_6_lb)
        self.tab_d_ms2threshold_spb = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.tab_d_ms2threshold_spb.setMaximum(99999)
        self.tab_d_ms2threshold_spb.setProperty("value", 10)
        self.tab_d_ms2threshold_spb.setObjectName("tab_d_ms2threshold_spb")
        self.horizontalLayout_5.addWidget(self.tab_d_ms2threshold_spb)
        self.tab_d_6_lb_2 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_6_lb_2.setObjectName("tab_d_6_lb_2")
        self.horizontalLayout_5.addWidget(self.tab_d_6_lb_2)
        self.tab_d_dda_spb = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.tab_d_dda_spb.setMinimum(1)
        self.tab_d_dda_spb.setMaximum(20)
        self.tab_d_dda_spb.setProperty("value", 12)
        self.tab_d_dda_spb.setObjectName("tab_d_dda_spb")
        self.horizontalLayout_5.addWidget(self.tab_d_dda_spb)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 5, 1, 1, 1)
        self.tab_d_1_lb = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_1_lb.setObjectName("tab_d_1_lb")
        self.gridLayout_3.addWidget(self.tab_d_1_lb, 0, 0, 1, 1)
        self.tab_d_xlsxpath_le = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.tab_d_xlsxpath_le.setObjectName("tab_d_xlsxpath_le")
        self.gridLayout_3.addWidget(self.tab_d_xlsxpath_le, 7, 1, 1, 1)
        self.tab_d_7_lb = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_7_lb.setObjectName("tab_d_7_lb")
        self.gridLayout_3.addWidget(self.tab_d_7_lb, 7, 0, 1, 1)
        self.tab_d_xlsxpath_pb = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.tab_d_xlsxpath_pb.setObjectName("tab_d_xlsxpath_pb")
        self.gridLayout_3.addWidget(self.tab_d_xlsxpath_pb, 7, 2, 1, 1)
        self.tab_d_ms2info_le = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.tab_d_ms2info_le.setObjectName("tab_d_ms2info_le")
        self.gridLayout_3.addWidget(self.tab_d_ms2info_le, 2, 1, 1, 1)
        self.tab_d_3_lb = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_3_lb.setObjectName("tab_d_3_lb")
        self.gridLayout_3.addWidget(self.tab_d_3_lb, 2, 0, 1, 1)
        self.tab_d_ms2info_pb = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.tab_d_ms2info_pb.setObjectName("tab_d_ms2info_pb")
        self.gridLayout_3.addWidget(self.tab_d_ms2info_pb, 2, 2, 1, 1)
        self.tab_d_ms2mzml_le = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.tab_d_ms2mzml_le.setObjectName("tab_d_ms2mzml_le")
        self.gridLayout_3.addWidget(self.tab_d_ms2mzml_le, 3, 1, 1, 1)
        self.tab_d_statusrun_pte = QtGui.QPlainTextEdit(self.gridLayoutWidget_3)
        self.tab_d_statusrun_pte.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tab_d_statusrun_pte.setObjectName("tab_d_statusrun_pte")
        self.gridLayout_3.addWidget(self.tab_d_statusrun_pte, 9, 1, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.tab_d_8_lb = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_8_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tab_d_8_lb.setObjectName("tab_d_8_lb")
        self.horizontalLayout_10.addWidget(self.tab_d_8_lb)
        self.tab_d_rtstart_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.tab_d_rtstart_dspb.setMaximum(300.0)
        self.tab_d_rtstart_dspb.setSingleStep(1.0)
        self.tab_d_rtstart_dspb.setProperty("value", 15.0)
        self.tab_d_rtstart_dspb.setObjectName("tab_d_rtstart_dspb")
        self.horizontalLayout_10.addWidget(self.tab_d_rtstart_dspb)
        self.tab_d_9_lb = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_9_lb.setObjectName("tab_d_9_lb")
        self.horizontalLayout_10.addWidget(self.tab_d_9_lb)
        self.tab_d_rtend_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.tab_d_rtend_dspb.setMaximum(300.0)
        self.tab_d_rtend_dspb.setProperty("value", 25.0)
        self.tab_d_rtend_dspb.setObjectName("tab_d_rtend_dspb")
        self.horizontalLayout_10.addWidget(self.tab_d_rtend_dspb)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem19)
        self.tab_d_10_lb = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_10_lb.setObjectName("tab_d_10_lb")
        self.horizontalLayout_10.addWidget(self.tab_d_10_lb)
        self.tab_d_mzstart_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.tab_d_mzstart_dspb.setDecimals(4)
        self.tab_d_mzstart_dspb.setMaximum(5000.0)
        self.tab_d_mzstart_dspb.setProperty("value", 600.0)
        self.tab_d_mzstart_dspb.setObjectName("tab_d_mzstart_dspb")
        self.horizontalLayout_10.addWidget(self.tab_d_mzstart_dspb)
        self.tab_d_11_lb = QtGui.QLabel(self.gridLayoutWidget_3)
        self.tab_d_11_lb.setObjectName("tab_d_11_lb")
        self.horizontalLayout_10.addWidget(self.tab_d_11_lb)
        self.tab_d_mzend_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.tab_d_mzend_dspb.setDecimals(4)
        self.tab_d_mzend_dspb.setMaximum(9000.0)
        self.tab_d_mzend_dspb.setProperty("value", 950.0)
        self.tab_d_mzend_dspb.setObjectName("tab_d_mzend_dspb")
        self.horizontalLayout_10.addWidget(self.tab_d_mzend_dspb)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem20)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 4, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 8, 1, 1, 1)
        self.tabframe.addTab(self.link_tab, "")
        self.hunter_tab = QtGui.QWidget()
        self.hunter_tab.setObjectName("hunter_tab")
        self.gridLayoutWidget_5 = QtGui.QWidget(self.hunter_tab)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 751, 441))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 1, 0, 1, 1)
        self.tab_e_statusrun_pte = QtGui.QPlainTextEdit(self.gridLayoutWidget_5)
        self.tab_e_statusrun_pte.setObjectName("tab_e_statusrun_pte")
        self.gridLayout_5.addWidget(self.tab_e_statusrun_pte, 14, 1, 1, 1)
        self.tab_e_loadxlsxpath_pb = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.tab_e_loadxlsxpath_pb.setObjectName("tab_e_loadxlsxpath_pb")
        self.gridLayout_5.addWidget(self.tab_e_loadxlsxpath_pb, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.tab_e_loadxlsxpath_le = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.tab_e_loadxlsxpath_le.setObjectName("tab_e_loadxlsxpath_le")
        self.gridLayout_5.addWidget(self.tab_e_loadxlsxpath_le, 1, 1, 1, 1)
        self.tab_e_ms2mzml_le = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.tab_e_ms2mzml_le.setObjectName("tab_e_ms2mzml_le")
        self.gridLayout_5.addWidget(self.tab_e_ms2mzml_le, 2, 1, 1, 1)
        self.tab_e_saveimgfolder_le = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.tab_e_saveimgfolder_le.setObjectName("tab_e_saveimgfolder_le")
        self.gridLayout_5.addWidget(self.tab_e_saveimgfolder_le, 4, 1, 1, 1)
        self.tab_d_runhunter_pb = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.tab_d_runhunter_pb.setObjectName("tab_d_runhunter_pb")
        self.gridLayout_5.addWidget(self.tab_d_runhunter_pb, 14, 0, 1, 1)
        self.tab_e_sumxlsxpath_le = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.tab_e_sumxlsxpath_le.setObjectName("tab_e_sumxlsxpath_le")
        self.gridLayout_5.addWidget(self.tab_e_sumxlsxpath_le, 5, 1, 1, 1)
        self.tab_e_ms2mzml_pb = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.tab_e_ms2mzml_pb.setObjectName("tab_e_ms2mzml_pb")
        self.gridLayout_5.addWidget(self.tab_e_ms2mzml_pb, 2, 2, 1, 1)
        self.tab_e_saveimgfolder_pb = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.tab_e_saveimgfolder_pb.setObjectName("tab_e_saveimgfolder_pb")
        self.gridLayout_5.addWidget(self.tab_e_saveimgfolder_pb, 4, 2, 1, 1)
        self.tab_e_sumxlsxpath_pb = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.tab_e_sumxlsxpath_pb.setObjectName("tab_e_sumxlsxpath_pb")
        self.gridLayout_5.addWidget(self.tab_e_sumxlsxpath_pb, 5, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 5, 0, 1, 1)
        self.line_5 = QtGui.QFrame(self.gridLayoutWidget_5)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_5.addWidget(self.line_5, 3, 1, 1, 1)
        self.line_6 = QtGui.QFrame(self.gridLayoutWidget_5)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_5.addWidget(self.line_6, 6, 1, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_20 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_16.addWidget(self.label_20)
        self.tab_e_score_spb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.tab_e_score_spb.setDecimals(1)
        self.tab_e_score_spb.setProperty("value", 27.5)
        self.tab_e_score_spb.setObjectName("tab_e_score_spb")
        self.horizontalLayout_16.addWidget(self.tab_e_score_spb)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem21)
        self.label_19 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_16.addWidget(self.label_19)
        self.tab_e_isotopescore_spb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.tab_e_isotopescore_spb.setDecimals(1)
        self.tab_e_isotopescore_spb.setProperty("value", 85.0)
        self.tab_e_isotopescore_spb.setObjectName("tab_e_isotopescore_spb")
        self.horizontalLayout_16.addWidget(self.tab_e_isotopescore_spb)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem22)
        self.gridLayout_5.addLayout(self.horizontalLayout_16, 11, 1, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        self.tab_e_rtstart_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.tab_e_rtstart_dspb.setProperty("value", 10.0)
        self.tab_e_rtstart_dspb.setObjectName("tab_e_rtstart_dspb")
        self.horizontalLayout_11.addWidget(self.tab_e_rtstart_dspb)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        self.tab_e_rtend_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.tab_e_rtend_dspb.setProperty("value", 25.0)
        self.tab_e_rtend_dspb.setObjectName("tab_e_rtend_dspb")
        self.horizontalLayout_11.addWidget(self.tab_e_rtend_dspb)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem23)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.tab_e_mzstart_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.tab_e_mzstart_dspb.setMaximum(1200.0)
        self.tab_e_mzstart_dspb.setProperty("value", 600.0)
        self.tab_e_mzstart_dspb.setObjectName("tab_e_mzstart_dspb")
        self.horizontalLayout_11.addWidget(self.tab_e_mzstart_dspb)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.tab_e_mzend_dspb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.tab_e_mzend_dspb.setMaximum(2000.0)
        self.tab_e_mzend_dspb.setProperty("value", 950.0)
        self.tab_e_mzend_dspb.setObjectName("tab_e_mzend_dspb")
        self.horizontalLayout_11.addWidget(self.tab_e_mzend_dspb)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem24)
        self.gridLayout_5.addLayout(self.horizontalLayout_11, 7, 1, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.tab_e_msthreshold_spb = QtGui.QSpinBox(self.gridLayoutWidget_5)
        self.tab_e_msthreshold_spb.setMaximum(999999)
        self.tab_e_msthreshold_spb.setProperty("value", 1000)
        self.tab_e_msthreshold_spb.setObjectName("tab_e_msthreshold_spb")
        self.horizontalLayout_12.addWidget(self.tab_e_msthreshold_spb)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self.tab_e_msppm_spb = QtGui.QSpinBox(self.gridLayoutWidget_5)
        self.tab_e_msppm_spb.setMaximum(9999)
        self.tab_e_msppm_spb.setProperty("value", 50)
        self.tab_e_msppm_spb.setObjectName("tab_e_msppm_spb")
        self.horizontalLayout_12.addWidget(self.tab_e_msppm_spb)
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem25)
        self.x = QtGui.QLabel(self.gridLayoutWidget_5)
        self.x.setObjectName("x")
        self.horizontalLayout_12.addWidget(self.x)
        self.tab_e_dda_spb = QtGui.QSpinBox(self.gridLayoutWidget_5)
        self.tab_e_dda_spb.setMaximum(20)
        self.tab_e_dda_spb.setProperty("value", 12)
        self.tab_e_dda_spb.setObjectName("tab_e_dda_spb")
        self.horizontalLayout_12.addWidget(self.tab_e_dda_spb)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem26)
        self.gridLayout_5.addLayout(self.horizontalLayout_12, 8, 1, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_17 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_13.addWidget(self.label_17)
        self.tab_e_hgthreshold_spb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.tab_e_hgthreshold_spb.setDecimals(0)
        self.tab_e_hgthreshold_spb.setMaximum(999999.0)
        self.tab_e_hgthreshold_spb.setProperty("value", 100.0)
        self.tab_e_hgthreshold_spb.setObjectName("tab_e_hgthreshold_spb")
        self.horizontalLayout_13.addWidget(self.tab_e_hgthreshold_spb)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_13.addWidget(self.label_18)
        self.tab_e_hgppm_spb = QtGui.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.tab_e_hgppm_spb.setDecimals(0)
        self.tab_e_hgppm_spb.setMaximum(9999.0)
        self.tab_e_hgppm_spb.setProperty("value", 200.0)
        self.tab_e_hgppm_spb.setObjectName("tab_e_hgppm_spb")
        self.horizontalLayout_13.addWidget(self.tab_e_hgppm_spb)
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem27)
        self.gridLayout_5.addLayout(self.horizontalLayout_13, 10, 1, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tab_e_lipidclass_cmb = QtGui.QComboBox(self.gridLayoutWidget_5)
        self.tab_e_lipidclass_cmb.setMinimumSize(QtCore.QSize(220, 0))
        self.tab_e_lipidclass_cmb.setObjectName("tab_e_lipidclass_cmb")
        self.tab_e_lipidclass_cmb.addItem("")
        self.tab_e_lipidclass_cmb.addItem("")
        self.tab_e_lipidclass_cmb.addItem("")
        self.tab_e_lipidclass_cmb.addItem("")
        self.tab_e_lipidclass_cmb.addItem("")
        self.tab_e_lipidclass_cmb.addItem("")
        self.tab_e_lipidclass_cmb.addItem("")
        self.tab_e_lipidclass_cmb.addItem("")
        self.horizontalLayout_7.addWidget(self.tab_e_lipidclass_cmb)
        spacerItem28 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem28)
        self.gridLayout_5.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.tab_d_ms2threshold_spb_2 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.tab_d_ms2threshold_spb_2.setObjectName("tab_d_ms2threshold_spb_2")
        self.horizontalLayout_15.addWidget(self.tab_d_ms2threshold_spb_2)
        self.tab_e_ms2threshold_spb = QtGui.QSpinBox(self.gridLayoutWidget_5)
        self.tab_e_ms2threshold_spb.setMaximum(999999)
        self.tab_e_ms2threshold_spb.setProperty("value", 100)
        self.tab_e_ms2threshold_spb.setObjectName("tab_e_ms2threshold_spb")
        self.horizontalLayout_15.addWidget(self.tab_e_ms2threshold_spb)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_15.addWidget(self.label_16)
        self.tab_e_ms2ppm_spb = QtGui.QSpinBox(self.gridLayoutWidget_5)
        self.tab_e_ms2ppm_spb.setMaximum(9999)
        self.tab_e_ms2ppm_spb.setProperty("value", 200)
        self.tab_e_ms2ppm_spb.setObjectName("tab_e_ms2ppm_spb")
        self.horizontalLayout_15.addWidget(self.tab_e_ms2ppm_spb)
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem29)
        self.gridLayout_5.addLayout(self.horizontalLayout_15, 9, 1, 1, 1)
        self.line_7 = QtGui.QFrame(self.gridLayoutWidget_5)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_5.addWidget(self.line_7, 12, 1, 1, 1)
        self.tabframe.addTab(self.hunter_tab, "")
        self.cfg_tab = QtGui.QWidget()
        self.cfg_tab.setObjectName("cfg_tab")
        self.gridLayoutWidget_6 = QtGui.QWidget(self.cfg_tab)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 751, 211))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 0, 0, 1, 1)
        self.tab_f_savesettings_pb = QtGui.QPushButton(self.gridLayoutWidget_6)
        self.tab_f_savesettings_pb.setObjectName("tab_f_savesettings_pb")
        self.gridLayout_6.addWidget(self.tab_f_savesettings_pb, 3, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 1, 0, 1, 1)
        self.tab_f_fawhitelist_le = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.tab_f_fawhitelist_le.setObjectName("tab_f_fawhitelist_le")
        self.gridLayout_6.addWidget(self.tab_f_fawhitelist_le, 0, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 2, 0, 1, 1)
        self.tab_f_hgcfg_le = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.tab_f_hgcfg_le.setObjectName("tab_f_hgcfg_le")
        self.gridLayout_6.addWidget(self.tab_f_hgcfg_le, 1, 1, 1, 1)
        self.tab_f_scorecfg_le = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.tab_f_scorecfg_le.setObjectName("tab_f_scorecfg_le")
        self.gridLayout_6.addWidget(self.tab_f_scorecfg_le, 2, 1, 1, 1)
        self.tab_f_scorecfg_pb = QtGui.QPushButton(self.gridLayoutWidget_6)
        self.tab_f_scorecfg_pb.setObjectName("tab_f_scorecfg_pb")
        self.gridLayout_6.addWidget(self.tab_f_scorecfg_pb, 2, 2, 1, 1)
        self.tab_f_hgcfg_pb = QtGui.QPushButton(self.gridLayoutWidget_6)
        self.tab_f_hgcfg_pb.setObjectName("tab_f_hgcfg_pb")
        self.gridLayout_6.addWidget(self.tab_f_hgcfg_pb, 1, 2, 1, 1)
        self.tab_f_fawhitelist_pb = QtGui.QPushButton(self.gridLayoutWidget_6)
        self.tab_f_fawhitelist_pb.setObjectName("tab_f_fawhitelist_pb")
        self.gridLayout_6.addWidget(self.tab_f_fawhitelist_pb, 0, 2, 1, 1)
        self.tabframe.addTab(self.cfg_tab, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtGui.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(150, 10, 611, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_25 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_4.addWidget(self.label_25)
        self.label_26 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_4.addWidget(self.label_26)
        self.label_27 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_4.addWidget(self.label_27)
        self.label_28 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_4.addWidget(self.label_28)
        self.label_29 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_4.addWidget(self.label_29)
        self.label_37 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_4.addWidget(self.label_37)
        self.line_8 = QtGui.QFrame(self.tab)
        self.line_8.setGeometry(QtCore.QRect(10, 150, 751, 16))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_30 = QtGui.QLabel(self.tab)
        self.label_30.setGeometry(QtCore.QRect(20, 170, 391, 16))
        self.label_30.setObjectName("label_30")
        self.gridLayoutWidget_7 = QtGui.QWidget(self.tab)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(20, 190, 741, 41))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_34 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_34.setObjectName("label_34")
        self.gridLayout_7.addWidget(self.label_34, 0, 4, 1, 1)
        self.label_35 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_35.setObjectName("label_35")
        self.gridLayout_7.addWidget(self.label_35, 0, 5, 1, 1)
        self.label_31 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_31.setObjectName("label_31")
        self.gridLayout_7.addWidget(self.label_31, 0, 0, 1, 1)
        self.label_32 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_32.setObjectName("label_32")
        self.gridLayout_7.addWidget(self.label_32, 0, 2, 1, 1)
        self.label_33 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_33.setObjectName("label_33")
        self.gridLayout_7.addWidget(self.label_33, 0, 3, 1, 1)
        self.label_36 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_36.setObjectName("label_36")
        self.gridLayout_7.addWidget(self.label_36, 0, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 128, 128))
        self.pushButton.setMinimumSize(QtCore.QSize(128, 128))
        self.pushButton.setMaximumSize(QtCore.QSize(128, 128))
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/LipidHunter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(128, 128))
        self.pushButton.setObjectName("pushButton")
        self.tabframe.addTab(self.tab, "")
        self.logo_lb = QtGui.QLabel(self.centralwidget)
        self.logo_lb.setGeometry(QtCore.QRect(10, 540, 491, 16))
        self.logo_lb.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.logo_lb.setObjectName("logo_lb")
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 231, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_23 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_14.addWidget(self.label_23)
        self.vendor_waters_rb = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.vendor_waters_rb.setChecked(True)
        self.vendor_waters_rb.setObjectName("vendor_waters_rb")
        self.horizontalLayout_14.addWidget(self.vendor_waters_rb)
        self.vendor_thermo_rb = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.vendor_thermo_rb.setChecked(False)
        self.vendor_thermo_rb.setObjectName("vendor_thermo_rb")
        self.horizontalLayout_14.addWidget(self.vendor_thermo_rb)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(250, 0, 341, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_24 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_18.addWidget(self.label_24)
        self.mode_lcms_rb = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        self.mode_lcms_rb.setChecked(True)
        self.mode_lcms_rb.setAutoExclusive(True)
        self.mode_lcms_rb.setObjectName("mode_lcms_rb")
        self.horizontalLayout_18.addWidget(self.mode_lcms_rb)
        self.mode_static_rb = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        self.mode_static_rb.setChecked(False)
        self.mode_static_rb.setObjectName("mode_static_rb")
        self.horizontalLayout_18.addWidget(self.mode_static_rb)
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem30)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabframe.setCurrentIndex(0)
        self.tab_d_lipidclass_cmb.setCurrentIndex(2)
        self.tab_e_lipidclass_cmb.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "LipidHunter (beta) | University of Leipzig ", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_savexlsxfolder_pb.setText(QtGui.QApplication.translate("MainWindow", "Save to folder", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_7_lb.setText(QtGui.QApplication.translate("MainWindow", "Merge to CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_clearall_pb.setText(QtGui.QApplication.translate("MainWindow", "Clear all", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_addmzml_pb.setText(QtGui.QApplication.translate("MainWindow", "Add single file", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_3_lb.setText(QtGui.QApplication.translate("MainWindow", "Add folder", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_addmzmlfolder_pb.setText(QtGui.QApplication.translate("MainWindow", "Select a folder", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_10_lb.setText(QtGui.QApplication.translate("MainWindow", "m/z range:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_11_lb.setText(QtGui.QApplication.translate("MainWindow", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_5_lb.setText(QtGui.QApplication.translate("MainWindow", "Output as Excel", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_2_lb.setText(QtGui.QApplication.translate("MainWindow", "Input .mzML file:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_runextractor_pb.setText(QtGui.QApplication.translate("MainWindow", "Run Extract", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_savecsv_pb.setText(QtGui.QApplication.translate("MainWindow", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_1_lb.setText(QtGui.QApplication.translate("MainWindow", "Step 1", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_6_lb.setText(QtGui.QApplication.translate("MainWindow", "Step 2", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_runmerge_pb.setText(QtGui.QApplication.translate("MainWindow", "Run Merge", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_8_lb.setText(QtGui.QApplication.translate("MainWindow", "rt range (min):", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_9_lb.setText(QtGui.QApplication.translate("MainWindow", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_a_4_lb.setText(QtGui.QApplication.translate("MainWindow", "MS level threshold(absolute):", None, QtGui.QApplication.UnicodeUTF8))
        self.tabframe.setTabText(self.tabframe.indexOf(self.extract_ms_level_tab), QtGui.QApplication.translate("MainWindow", "1. Extract MS level", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_clearall_pb.setText(QtGui.QApplication.translate("MainWindow", "Clear all", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_3_lb.setText(QtGui.QApplication.translate("MainWindow", "MS level threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_4_lb.setText(QtGui.QApplication.translate("MainWindow", "MS2 Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_6_lb.setText(QtGui.QApplication.translate("MainWindow", "DDA top:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_1_lb.setText(QtGui.QApplication.translate("MainWindow", "Input .mzML file:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_savexlsxfolder_pb.setText(QtGui.QApplication.translate("MainWindow", "Save to folder", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_5_lb.setText(QtGui.QApplication.translate("MainWindow", "Output as Excel", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_runextract_pb.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_addmzml_pb.setText(QtGui.QApplication.translate("MainWindow", "Add single file", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_2_lb.setText(QtGui.QApplication.translate("MainWindow", "Add folder", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_addmzmlfolder_pb.setText(QtGui.QApplication.translate("MainWindow", "Select a folder", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_8_lb.setText(QtGui.QApplication.translate("MainWindow", "rt range (min):", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_11_lb.setText(QtGui.QApplication.translate("MainWindow", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_10_lb.setText(QtGui.QApplication.translate("MainWindow", "m/z range:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_b_9_lb.setText(QtGui.QApplication.translate("MainWindow", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Excel output generated will be used in step 4 as \"MS2 scan info\"", None, QtGui.QApplication.UnicodeUTF8))
        self.tabframe.setTabText(self.tabframe.indexOf(self.scan_info_tab), QtGui.QApplication.translate("MainWindow", "2. Extract Scan info", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_c_5_lb.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><a href=\"http://www.lipidmaps.org/tools/ms/glycerolipids_batch_bulk.html\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.lipidmaps.org/tools/ms/glycerolipids_batch_bulk.html</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_c_1_lb.setText(QtGui.QApplication.translate("MainWindow", "Search on LipidMaps", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_c_2_lb.setText(QtGui.QApplication.translate("MainWindow", "For Glycerol phospholipids:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_c_4_lb.setText(QtGui.QApplication.translate("MainWindow", "For Triacylglycerols:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_c_3_lb.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><a href=\"http://www.lipidmaps.org/tools/ms/glycerophospholipids_batch_bulk.html\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.lipidmaps.org/tools/ms/glycerophospholipids_batch_bulk.html</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabframe.setTabText(self.tabframe.indexOf(self.search_tab), QtGui.QApplication.translate("MainWindow", "3. Bulk Search", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_4_lb.setText(QtGui.QApplication.translate("MainWindow", "Whole spectra .mzML", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_runextract_pb.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_lipidclass_cmb.setItemText(0, QtGui.QApplication.translate("MainWindow", "Phosphatidic acid (PA) [M-H]-", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_lipidclass_cmb.setItemText(1, QtGui.QApplication.translate("MainWindow", "Phosphatidylethanolamine (PE) [M-H]-", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_lipidclass_cmb.setItemText(2, QtGui.QApplication.translate("MainWindow", "Phosphatidylcholine (PC) [M+HCOO]-", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_lipidclass_cmb.setItemText(3, QtGui.QApplication.translate("MainWindow", "Phosphatidylglycerol (PG) [M-H]-", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_lipidclass_cmb.setItemText(4, QtGui.QApplication.translate("MainWindow", "Phosphatidylserine (PS) [M-H]-", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_lipidclass_cmb.setItemText(5, QtGui.QApplication.translate("MainWindow", "Phosphatidylinositol (PI) [M-H]-", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_lipidclass_cmb.setItemText(6, QtGui.QApplication.translate("MainWindow", "Triacylglycerol (TG) [M+H]+", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_lipidclass_cmb.setItemText(7, QtGui.QApplication.translate("MainWindow", "Triacylglycerol (TG) [M+NH4]+", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_ms2mzml_pb.setText(QtGui.QApplication.translate("MainWindow", "Select file", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_lipidstable_pb.setText(QtGui.QApplication.translate("MainWindow", "Select file", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_2_lb.setText(QtGui.QApplication.translate("MainWindow", "Bulk search result", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_5_lb.setText(QtGui.QApplication.translate("MainWindow", "MS level threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Selection window+/- (m/z):", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_6_lb.setText(QtGui.QApplication.translate("MainWindow", "MS2 Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_6_lb_2.setText(QtGui.QApplication.translate("MainWindow", "DDA top:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_1_lb.setText(QtGui.QApplication.translate("MainWindow", "Select lipid class", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_7_lb.setText(QtGui.QApplication.translate("MainWindow", "Output as Excel", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_xlsxpath_pb.setText(QtGui.QApplication.translate("MainWindow", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_3_lb.setText(QtGui.QApplication.translate("MainWindow", "MS2 scan info", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_ms2info_pb.setText(QtGui.QApplication.translate("MainWindow", "Select file", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_8_lb.setText(QtGui.QApplication.translate("MainWindow", "rt range (min):", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_9_lb.setText(QtGui.QApplication.translate("MainWindow", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_10_lb.setText(QtGui.QApplication.translate("MainWindow", "m/z range:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_11_lb.setText(QtGui.QApplication.translate("MainWindow", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Excel output generated will be used in step 5 as \"Linked info\".", None, QtGui.QApplication.UnicodeUTF8))
        self.tabframe.setTabText(self.tabframe.indexOf(self.link_tab), QtGui.QApplication.translate("MainWindow", "4. Link lipids to scans", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Linked info.", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_e_loadxlsxpath_pb.setText(QtGui.QApplication.translate("MainWindow", "Select file", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Select lipid class", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_runhunter_pb.setText(QtGui.QApplication.translate("MainWindow", "Run LipidHunter", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_e_ms2mzml_pb.setText(QtGui.QApplication.translate("MainWindow", "Select file", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_e_saveimgfolder_pb.setText(QtGui.QApplication.translate("MainWindow", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_e_sumxlsxpath_pb.setText(QtGui.QApplication.translate("MainWindow", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Spectra .mzML", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Output folder", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Export summary table", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Score filter:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Isotope score filter:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "rt range (min):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "m/z range:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "MS level threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "MS level ppm:", None, QtGui.QApplication.UnicodeUTF8))
        self.x.setText(QtGui.QApplication.translate("MainWindow", "DDA Top", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Specific peaks threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Specific peaks ppm", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_e_lipidclass_cmb.setItemText(0, QtGui.QApplication.translate("MainWindow", "Phosphatidic acid (PA) [M-H]-", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_e_lipidclass_cmb.setItemText(1, QtGui.QApplication.translate("MainWindow", "Phosphatidylethanolamine (PE) [M-H]-", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_e_lipidclass_cmb.setItemText(2, QtGui.QApplication.translate("MainWindow", "Phosphatidylcholine (PC) [M+HCOO]-", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_e_lipidclass_cmb.setItemText(3, QtGui.QApplication.translate("MainWindow", "Phosphatidylglycerol (PG) [M-H]-", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_e_lipidclass_cmb.setItemText(4, QtGui.QApplication.translate("MainWindow", "Phosphatidylserine (PS) [M-H]-", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_e_lipidclass_cmb.setItemText(5, QtGui.QApplication.translate("MainWindow", "Phosphatidylinositol (PI) [M-H]-", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_e_lipidclass_cmb.setItemText(6, QtGui.QApplication.translate("MainWindow", "Triacylglycerol (TG) [M+H]+", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_e_lipidclass_cmb.setItemText(7, QtGui.QApplication.translate("MainWindow", "Triacylglycerol (TG) [M+NH4]+", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_d_ms2threshold_spb_2.setText(QtGui.QApplication.translate("MainWindow", "MS2 level threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "MS2 level ppm:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabframe.setTabText(self.tabframe.indexOf(self.hunter_tab), QtGui.QApplication.translate("MainWindow", "5. Generate assigned spectra", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Fatty acid white list:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_f_savesettings_pb.setText(QtGui.QApplication.translate("MainWindow", "Save above settings as defaullt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Lipid specific FRAG & NL :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Score weight settings:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_f_scorecfg_pb.setText(QtGui.QApplication.translate("MainWindow", "Select file", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_f_hgcfg_pb.setText(QtGui.QApplication.translate("MainWindow", "Select file", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_f_fawhitelist_pb.setText(QtGui.QApplication.translate("MainWindow", "Select file", None, QtGui.QApplication.UnicodeUTF8))
        self.tabframe.setTabText(self.tabframe.indexOf(self.cfg_tab), QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "LipidHunter Beta relased date: 18, Jan, 2017", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Developed by: LPPdb team", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "License GPL v2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Project page:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Online tutorial:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "Please cite our publication:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "We acknolege to all the open source libraries used in LipidHunter:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "pyside", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "scipy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "matplotlib", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "pandas", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "pymzML", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "numpy", None, QtGui.QApplication.UnicodeUTF8))
        self.tabframe.setTabText(self.tabframe.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.logo_lb.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>LipidHunter (c) 2015-2017 | <a href=\"http://www.zv.uni-leipzig.de/\"><span style=\" text-decoration: underline; color:#0000ff;\">University of Leipzig</span></a> | <a href=\"http://research.uni-leipzig.de/bioanalytik/\"><span style=\" text-decoration: underline; color:#0000ff;\">AG Bioanalytik</span></a> | <a href=\"https://home.uni-leipzig.de/fedorova/\"><span style=\" text-decoration: underline; color:#0000ff;\">Fedorova Research Group</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Instrument vendor:", None, QtGui.QApplication.UnicodeUTF8))
        self.vendor_waters_rb.setText(QtGui.QApplication.translate("MainWindow", "Waters", None, QtGui.QApplication.UnicodeUTF8))
        self.vendor_thermo_rb.setText(QtGui.QApplication.translate("MainWindow", "Thermo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.mode_lcms_rb.setText(QtGui.QApplication.translate("MainWindow", "LC-MS/MS", None, QtGui.QApplication.UnicodeUTF8))
        self.mode_static_rb.setText(QtGui.QApplication.translate("MainWindow", "Static measurement", None, QtGui.QApplication.UnicodeUTF8))

import LipidHunter_rcc
